version: '2'

services:
  api:
    build: .
    image: ddmax/zjnucloud-api
    container_name: zjnucloud-api
    ports:
        - "80:80"
    entrypoint: /opt/django/run.sh
    environment:
        - MODULE=zjnucloud-api
        - DB_HOST=mysql
        - DB_USERNAME=mysql
        - DB_PASSWORD=mysql
        - DB_NAME=zjnucloud-api
    links:
        - db:mysql
    depends_on:
        - "db"
  db:
    image: mysql:5.5
    container_name: zjnucloud-api-mysql
    restart: always
    environment:
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=mysql
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=zjnucloud-api